version: "3.8"

services: 

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - laravel-volume:/var/www/html
    networks:
      - app-net

volumes:
   laravel-volume:

networks:
  app-net:
    driver: bridge